version: "3"
services:
  web:
    build: .
    #command: gunicorn -b 0.0.0.0:8000 hello:app --reload #to deploy
    command: flask run --host=0.0.0.0 --port=8000
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "8000:8000"
    volumes:
      - ./:/root